# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: ubs-tst-api_development

test:
  <<: *default
  database: ubs-tst-api_test

production:
  <<: *default
  database: ubs-tst-api_production
  username: <%= ENV['DATABASE_USER_PRD'] %>
  password: <%= ENV['DATABASE_PASSWORD_PRD'] %>
